version: "3.6"
name: cosmos-rpc
services:
    load-balancer:
        build:
            context: ./haproxy
            dockerfile: Dockerfile
        container_name: load-balancer
        hostname: load-balancer
        image: load-balancer
        restart: always
        ports:
            - 26657:26657
            - 1317:1317
        command: [nginx-debug, "-g", "daemon off;"]
    node1:
        build:
            context: ./node
            dockerfile: Dockerfile
            args:
                GO_VERSION: 1.19.7
                BINARY_VERSION: v0.8.7
        container_name: node1
        hostname: node1
        ports:
            - 10001:1317
            - 10002:6060
            - 10003:8080
            - 10004:9090
            - 10005:9091
            - 10006:26656
            - 10007:26657
            - 10008:26658
            - 10009:26660
            - 10010:55667
        image: node
        restart: always
    # node2:
    #     image: node
    #     container_name: node2
    #     hostname: node2
    #     ports:
    #         - 20001:1317
    #         - 20002:6060
    #         - 20003:8080
    #         - 20004:9090
    #         - 20005:9091
    #         - 20006:26656
    #         - 20007:26657
    #         - 20008:26658
    #         - 20009:26660
    #         - 20010:55667
    #     restart: always
networks:
    default:
        name: cosmos-net
        external: true
