version: "3.6"
name: cosmos-rpc
services:
    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        container_name: nginx
        hostname: nginx
        image: nginx
        restart: always
        ports:
            - 8080:80
    load-balancer:
        build:
            context: ./haproxy
            dockerfile: Dockerfile
        container_name: load-balancer
        hostname: load-balancer
        image: load-balancer
        restart: always
        ports:
            - 26657:26657
            - 1317:1317
    node1:
        build:
            context: ./node
            dockerfile: Dockerfile
            args:
                GO_VERSION: 1.19.7
                BINARY_VERSION: v0.8.7
        container_name: node1
        hostname: node1
        image: node
        restart: always
    node2:
        image: node
        container_name: node2
        hostname: node2
        restart: always
    node3:
        image: node
        container_name: node3
        hostname: node3
        restart: always
    node4:
        image: node
        container_name: node4
        hostname: node4
        restart: always
    node5:
        image: node
        container_name: node5
        hostname: node5
        restart: always
    node6:
        image: node
        container_name: node6
        hostname: node6
        restart: always
    node7:
        image: node
        container_name: node7
        hostname: node7
        restart: always
    node8:
        image: node
        container_name: node8
        hostname: node8
        restart: always
    node9:
        image: node
        container_name: node9
        hostname: node9
        restart: always
    node10:
        image: node
        container_name: node10
        hostname: node10
        restart: always
    node11:
        image: node
        container_name: node11
        hostname: node11
        restart: always
    node12:
        image: node
        container_name: node12
        hostname: node12
        restart: always
networks:
    default:
        name: cosmos-net
        external: true
